version: '3'

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: '52.87.175.0'  
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://52.87.175.0'  
    ports:
      - '80:80'
      - '443:443'
      - "2222:22"
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'

